# Role Requirements are placed here. Some examples are below:

- src: stancel.create-digitalocean-droplet

# Switched to using NginX
#- src: stancel.apache-webserver

- src: oefenweb.percona_server

- src: stancel.setup-mysql-backups

- src: stancel.install-bareos-client
  
- src: stancel.add-job-to-bareos-director

- src: stancel.install-nagios-client

- src: stancel.add-config-to-nagios-server

- src: stancel.git_download_wordpress

- src: stancel.restore_bareos_backup

- src: stancel.restore_db_and_files

- src: stancel.git_deploy_setup

- src: stancel.nginx_install

- src: stancel.nginx_site_setup

- src: stancel.certbot_install

- src: stancel.install_certbot_ssl_certs

- src: stancel.add_digitalocean_dns_entries

- src: sbaerlocher.wp-cli

- src: stancel.finish_wordpress_restore

- src: stancel.set_wordpress_permissions
